---
title: History of Italy with Chinese Characteristics
timezone: Europe/Rome
collections:
  posts_cn:
    title: Chinese Post
    output: true
  posts_en:
    title: English Posts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post_en
    permalink: '/posts_en/:title/'
- scope:
    path: ''
    type: posts_en
  values:
    layout: post_en
    permalink: "/posts_en/:title/"
- scope:
    path: ''
    type: posts_cn
  values:
    layout: post_cn
    permalink: "/posts_cn/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
